### ISSUE TITLE
Errors on decompile/compile

### ISSUE THREAD

**Issue by Ketrel** [Furniel/Apk-Changer#13]
Right now I'm just trying to decompile/recompile without any changes (yet).

What I did.

1. Downloaded the latest release
2. Downloading this: https://fbreader.org/files/android/FBReaderJ_ice-cream-sandwich.apk
3. Installed APK Changer with recommended settings
4. Chose to decompile apk/jar

Doing that produces the following log

    ------------------------------------------------------------------------- 
    -----------------------|Mon 02/13/2017 -- 15:39:29.25|----------------------- 
    ------------------------------------------------------------------------- 
    The system cannot find the file specified.
    java version "1.8.0_121"
    Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
    ########################################################################
    I: Decompiling FBReaderJ_ice-cream-sandwich...

    Command Line Error:
    Incorrect wildcard type marker
    *.dex
    I: Baksmaling classes.dex...
    I: FBReaderJ_ice-cream-sandwich decompiled
    ########################################################################

Trying to compile fails with a much larger error.

Many lines, most of them similar to

    W: C:\ApkChanger\out\FBReaderJ_ice-cream-sandwich\res\layout-v17\abc_alert_dialog_button_bar_material.xml:2: error: No resource identifier found for attribute 'layoutDirection' in package 'android'

**Comment by Furniel** [comment]
I recommend you update apkchanger to latest version(option 14 in settings menu or 2014 in main menu) to fix(were fixed in latest updates) this warnings:

> The system cannot find the file specified.

and

> Command Line Error:
> Incorrect wildcard type marker
> *.dex"

But this warnings not related to compilation problem.

Errors like this

> No resource identifier found for attribute 'layoutDirection' in package 'android'

 means that wrong framework was used for apk decompilation. [LayoutDirection](https://developer.android.com/reference/android/util/LayoutDirection.html) was added in api 19(android 4.4), so check what framework version you are using. Tested decompilation\compilation with android 7.1 framework - everything loolks fine:
```
-------------------------------------------------------------------------
-----------------------|14.02.2017 -- 13:33:06,29|-----------------------
-------------------------------------------------------------------------
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
########################################################################
I: Decompiling FBReaderJ_ice-cream-sandwich...
I: Baksmaling classes.dex...
I: FBReaderJ_ice-cream-sandwich decompiled
########################################################################
########################################################################
I: Compiling FBReaderJ_ice-cream-sandwich...
I: Optimizing images...
I: Saved 210kb
I: Recompressing with 7zip...
I: Zipaligning...
I: Signing apk with testkey...
I: FBReaderJ_ice-cream-sandwich compiled.
########################################################################
```

**Comment by Ketrel** [comment]
Is there a version newer than 2.1.1 in releases, because that's the one I used (or do you mean cloning master)?

**Comment by Furniel** [comment]
Releases were made just for easy installation of the program and 2.1.1 it's release version, but not program version(i can't create releases after each program update). Program don't have versions and I always recommend use latest version. For easy updates program have option 14(Check for program updates), if you select this option program automatically downloads and installs latest updates from github(of course you can clone master manually, but it's easier to use proper option).
PS: In last update i added automatic framework selection in framework options.
