### ISSUE TITLE
2 errors when install

### ISSUE THREAD

**Issue by ctlui** [Furniel/Apk-Changer#15]
Hi,
I got this errors when I try to install (v2.1.1) on windows10
I don't uderstand what is write as I can't read Russian.
Thanks.
Eric
![Uploading apkchanger_error2.jpg…]()
![Uploading apkchanger_error1.jpg…]()

**Comment by Furniel** [comment]
Something wrong with uploaded images, so i don't see errors. Installer supports two languages and it should automatically detect language used by your system. Uploaded new installer, set English language as default(hope this will fix issue with russian language). If you can't install program via installer, you can simply download this repo or clone it.

**Comment by ctlui** [comment]
Here's the img errors


![apkchanger_error1](https://cloud.githubusercontent.com/assets/11196998/24416432/132a80c4-13e5-11e7-99b3-b4470daaf42e.jpg)
![apkchanger_error2](https://cloud.githubusercontent.com/assets/11196998/24416433/132c8bda-13e5-11e7-87e9-2c40fb8825d7.jpg)

**Comment by Furniel** [comment]
Oh that's surprise for me. Looks like a problem with antivirus. I used compressor for some exe files, checked them now on virustotal and some antiviruses detect this exe files as Trojan executables. Disabled binaries compression and uploaded new release, hope this will fix all issues.

**Comment by ctlui** [comment]
Last version solved the problem.
Installed, tested, runing ok.
Thanks
