### ISSUE TITLE
Flashable zip creator

### ISSUE THREAD

**Issue by irpongky** [Furniel/Apk-Changer#19]
Can you add feature apk and service.jar flashable zip flashing from twrp?
Specifically can flash apk push /system/priv-app and service.jar push /system/framework
I love your tools all in one

**Comment by Furniel** [comment]
I will think about this enhancement - main goal if this tool is apk\jar decompilation and compilation, not flashable zip creation. And i'm not sure that flashable zip creation via program will be easier than manual zip creation. Manually you can drag and drop apks to necessary folders and than compress archive but in program it will be something like this:
1) select apk or jar
2) select where to flash apk\jar(app, priv-app or framework)
3) if selected app or priv-app - select apk folder name(we can't be sure that folder name is same as apk name). And even worther  - for old roms we don't need this at all - all apk's must be flashed there directly to app(priv-app folder) without any subfolders, so we must check this in some way too.
4) if user want flash more than one apk\jar goto step one
I think that manual flashable zip creation will be faster and easier than such implementation.

**Comment by irpongky** [comment]
Thanks you
