### ISSUE TITLE
App closing- Nothing is happening

### ISSUE THREAD

**Issue by jack16099** [Furniel/Apk-Changer#7]
Hello, tried this app and used all recommended settings. placed apk inside place-files-here-for-modding folder but after selecting res compression, app is closing and nothing is happening. Don't know what's wrong. No error message.  using the latest version. windows 7 32 bit

**Comment by Furniel** [comment]
Made many tests of new installed app, hope i found bug that caused app closing in your case.

**Comment by jack16099** [comment]
Yes. It's working now. Thanks.
btw, i faced another problem too. apkchanger wasn't able to start because it was unable to find path of 'find" and another file. This is how to fix it. click start- right click computer- properties- advanced system settings- environment variables (bottom), under system variables, there's something called "path". click it and click edit. add the following line into the beginning of it and then click ok.

C:\WINDOWS\system32;

(mine looked like this after adding the above line C:\WINDOWS\system32;C:\Program Files\Java\jre7\bin )

Hope this helps somebody.
