### ISSUE TITLE
Deodexing does not work properly on some files.

### ISSUE THREAD

**Issue by matejdro** [Furniel/Apk-Changer#8]
Deodexing does not work with some files using the tool. I copied in full `app`, `priv-app` and `framework` dump of the device, and yet it listed bunch of `Can't deodex <App name here>` lines into `Deodex_errors.txt˙`

Procedure/script from this repository works fine, so it is not the issue in the files: https://github.com/cofface/android_deodex

Example broken file: https://dl.dropboxusercontent.com/u/6999250/deodex.7z

**Comment by Furniel** [comment]
Now i`m working on update of deodexing code (i need to add support of android 6, 7, 7.1 files and not break support of android 2, 4, and 5). There are couple of problems, but i hope that i`ll fix all of them and update will be ready soon.

**Comment by Furniel** [comment]
Ок, looks like bug is fixed now. Broken files from this issue now can be deodexed. All roms(android 2.3 - 7.1.1) from https://developers.google.com/android/images now can be deodex too.
Update will be released after few more tests...

**Comment by matejdro** [comment]
Just tested this out and it works perfectly.

Thanks a lot for your work on this tool, it is really helpful!
